language: java

script: mvn test -B clean verify install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
